// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiSistemaControlePedidos.Migrations
{
    [DbContext(typeof(SistemaContext))]
    [Migration("20250215004735_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("ApiSistemaControlePedidos.Models.HorariosFuncionamentoModel", b =>
                {
                    b.Property<int>("IdHorarioFuncionamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HorarioFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HorarioInicio")
                        .HasColumnType("TEXT");

                    b.HasKey("IdHorarioFuncionamento");

                    b.ToTable("HorariosFuncionamentoModel");
                });

            modelBuilder.Entity("ApiSistemaControlePedidos.Models.ItensPedidoModel", b =>
                {
                    b.Property<int>("IdItenPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPedido")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdProduto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PedidoModelIdPedido")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Qtd")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdItenPedido");

                    b.HasIndex("PedidoModelIdPedido");

                    b.ToTable("ItensPedidoModel");
                });

            modelBuilder.Entity("ApiSistemaControlePedidos.Models.PedidoModel", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DtRegister")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<short>("IdStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPedido");

                    b.ToTable("PedidoModel");
                });

            modelBuilder.Entity("ApiSistemaControlePedidos.Models.ProdutosModel", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTipoProduto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdProduto");

                    b.ToTable("ProdutosModel");
                });

            modelBuilder.Entity("ApiSistemaControlePedidos.Models.StatusPedidoModel", b =>
                {
                    b.Property<short>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdStatus");

                    b.ToTable("StatusPedidoModel");
                });

            modelBuilder.Entity("ApiSistemaControlePedidos.Models.TiposProdutoModel", b =>
                {
                    b.Property<int>("IdTipoProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdTipoProduto");

                    b.ToTable("TiposProdutoModel");
                });

            modelBuilder.Entity("ApiSistemaControlePedidos.Models.ItensPedidoModel", b =>
                {
                    b.HasOne("ApiSistemaControlePedidos.Models.PedidoModel", null)
                        .WithMany("ItensPedido")
                        .HasForeignKey("PedidoModelIdPedido");
                });

            modelBuilder.Entity("ApiSistemaControlePedidos.Models.PedidoModel", b =>
                {
                    b.Navigation("ItensPedido");
                });
#pragma warning restore 612, 618
        }
    }
}
